# Generated by Django 3.2.4 on 2022-05-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_alter_orders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='whole_price',
            field=models.FloatField(default=0.0),
        ),
    ]
