# Generated by Django 3.2.4 on 2022-05-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_member_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shop_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
